consul-client:
  image: outstand/consul:latest
  restart: always
  labels:
    - io.rancher.os.scope=system
    - io.rancher.os.after=wait-for-network
    - io.rancher.os.before=docker
    - io.rancher.os.reloadconfig=true
    - io.rancher.os.remove=false
  net: host
  container_name: consul
  command: agent -ui -join=${CONSUL_JOIN_ADDRESS}
  environment:
    CONSUL_BIND_INTERFACE: eth0
    CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
