consul:
  image: consul:0.9.2
  restart: always
  labels:
    - io.rancher.os.remove=false
  net: host
  command: agent -ui -join=${CONSUL_JOIN_ADDRESS}
  environment:
    CONSUL_BIND_INTERFACE: eth0
    CONSUL_CLIENT_INTERFACE: eth0
