consul:
  image: consul:1.0.2
  restart: always
  labels:
    - io.rancher.os.remove=false
  net: host
  command: agent -server -ui -bootstrap
  environment:
    CONSUL_BIND_INTERFACE: eth0
    CONSUL_CLIENT_INTERFACE: eth0
