parallels-tools:
  image: outstand/parallels-tools:14.0.0.45124
  restart: always
  labels:
    - io.rancher.os.remove=false
    - io.rancher.os.after=kernel-headers
  volumes:
    - /usr/src:/usr/src
    - /lib/modules:/lib/modules
  privileged: true
