portainer:
  image: portainer/portainer:latest
  ports:
    - "9000:9000"
  command: ["-H", "unix:///var/run/docker.sock", "--admin-password", "$$2y$$05$$ThVS3sPtTDLQMmrtUjhE6uIs8xxj1lgNY0xQ6oUy8Kogy4H6qKdcO"]
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/portainer/data:/data
