---
:preferences:
  :proxy_disabled: false
  :fsevents_disabled: false
  :create:
    provider: parallels
    boot2docker_url: https://github.com/rancher/os/releases/download/v0.4.3/rancheros.iso
    memory: 4096
  :machine_name: default
  :dinghy_domain: dev
