---
:preferences:
  :proxy_disabled: false
  :fsevents_disabled: false
  :create:
    provider: parallels
    boot2docker_url: https://releases.rancher.com/os/v1.0.1/rancheros.iso
    memory: 5116
    disk: 60000
    cpus: 4
  :machine_name: default
  :dinghy_domain: dev
