---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      become: yes

    - name: Install apt https support
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: yes

    - name: Install docker apt key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
      become: yes

    - shell: /usr/bin/lsb_release -cus
      register: upstream_version

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ upstream_version.stdout }} stable
      become: yes

    - name: Install docker
      apt:
        name: docker-ce
        state: latest
      become: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: yes

    - name: Download docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
        checksum: sha256:f679a24b93f291c3bffaff340467494f388c0c251649d640e661d509db9d57e9
      become: yes

    - name: Install ruby
      apt:
        name: ruby ruby-bundler
        state: latest
      become: yes

    - name: Install dory
      bundler:
        chdir: "{{ dev_env_dir }}/ansible"
        user_install: no
      become: yes

    - name: Install desk
      get_url:
        url: https://raw.githubusercontent.com/outstand/desk/master/desk
        dest: /usr/local/bin/desk
        mode: 0755
      become: yes

    - name: Install zsh
      apt:
        name: zsh
        state: latest
      become: yes

    - name: Install dory preferences
      copy:
        src: "{{ dev_env_dir }}/docker/dory.yml"
        dest: ~/.dory.yml

    - name: Add dash to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "source {{ dev_env_dir }}/ansible/dash_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add dash to .bashrc
      lineinfile:
        dest: "{{ item }}"
        line: "source {{ dev_env_dir }}/ansible/dash_profile"
        create: yes
      loop:
        - ~/.bash_profile
        - ~/.bashrc
      when: ansible_env.SHELL == "/bin/bash"

    - name: Add desk to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: '[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true'
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add desk to .bashrc
      lineinfile:
        dest: "{{ item }}"
        line: '[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true'
        create: yes
      loop:
        - ~/.bash_profile
        - ~/.bashrc
      when: ansible_env.SHELL == "/bin/bash"

    - name: Ensure ~/.irb_history exists
      copy:
        content: ''
        dest: ~/.irb_history
        force: no
