---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo
      changed_when: false

    - name: Verify Parallels is installed
      shell: test -n "$(mdfind 'kMDItemCFBundleIdentifier == com.parallels.desktop.console')"
      changed_when: false

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap homebrew services
      homebrew_tap: tap=homebrew/services

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-machine
        - docker-machine-parallels
        - docker-compose
        - dnsmasq

    - name: Create resolver directory
      file: path=/etc/resolver state=directory mode=0755
      become: yes
      become_method: sudo

    - name: Create dev resolver file at /etc/resolver/dev
      file:
        src: "{{ dev_env_dir }}/ansible/resolver-dev.conf"
        dest: /etc/resolver/dev
        state: link
        force: yes
      become: yes
      become_method: sudo

    - name: Create dnsmasq configuration
      file:
        src: "{{ dev_env_dir }}/ansible/dnsmasq.conf"
        dest: /usr/local/etc/dnsmasq.conf
        state: link
        force: yes

    - name: Start dnsmasq
      command: brew services start dnsmasq
      become: yes
      become_method: sudo

    - name: Add NFS share to /etc/exports
      blockinfile:
        dest: /etc/exports
        create: yes
        marker: "## {mark} Dash Developer Environment - ANSIBLE MANAGED BLOCK ##"
        content: '/Users -network 10.211.55.0 -mask 255.255.255.0 -alldirs -mapall=0:80'
      become: yes
      become_method: sudo
      register: exports

    - name: Restart nfsd
      command: nfsd restart
      become: yes
      become_method: sudo
      when: exports.changed

    - name: Add Docker Machine Environment to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add Docker Machine Environment to .bash_profile
      lineinfile:
        dest: ~/.bash_profile
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/bash"
