---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:

    - name: Check Sudo Password
      command: ls
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap homebrew services
      homebrew_tap: tap=homebrew/services

    - name: Install Parallels
      homebrew_cask: name=parallels-desktop state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-machine
        - docker-machine-parallels
        - docker-compose

    - name: Create resolver directory
      file: path=/etc/resolver state=directory mode=0755
      become: yes
      become_method: sudo

    - name: Create dev resolver file at /etc/resolver/dev
      file:
        src: "{{ dev_env_dir }}/ansible/resolver-dev.conf"
        dest: /etc/resolver/dev
        state: link
        force: yes
      become: yes
      become_method: sudo

    - name: Add Docker Machine Environment to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add Docker Machine Environment to .bash_profile
      lineinfile:
        dest: ~/.bash_profile
        line: "source {{ dev_env_dir }}/ansible/mac_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/bash"
