---
- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:

    # - name: Check Sudo Password
    #   command: ls
    #   become: yes
    #   become_method: sudo
    #   changed_when: false

    - name: Verify Parallels is installed
      shell: test -n "$(mdfind 'kMDItemCFBundleIdentifier == com.parallels.desktop.console')"
      changed_when: false

    - name: Tap homebrew services
      homebrew_tap: tap=homebrew/services

    - name: Tap outstand/dinghy
      homebrew_tap: tap=outstand/dinghy state=present

    - name: Tap codekitchen/dinghy
      homebrew_tap: tap=codekitchen/dinghy state=present

    - name: Tap outstand/desk
      homebrew_tap: tap=outstand/desk state=present

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Remove docker
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker111
        - docker1103

    - name: Install Docker and Extras
      homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - docker-machine
        - docker-machine-parallels
        - docker-compose
        - outstand/dinghy/dinghy
        - outstand/desk/desk
        - zsh

    - name: Create dinghy preferences directory
      file: path=~/.dinghy state=directory

    - name: Install dinghy preferences
      copy: src={{ dev_env_dir}}/docker/dinghy-preferences.yml dest=~/.dinghy/preferences.yml

    - name: Add Docker Machine Environment to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "source {{ dev_env_dir }}/ansible/dash_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add Docker Machine Environment to .bash_profile
      lineinfile:
        dest: ~/.bash_profile
        line: "source {{ dev_env_dir }}/ansible/dash_profile"
        create: yes
      when: ansible_env.SHELL == "/bin/bash"

    - name: Add desk to .zshrc
      lineinfile:
        dest: ~/.zshrc
        line: '[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true'
        create: yes
      when: ansible_env.SHELL == "/bin/zsh" or ansible_env.SHELL == "/usr/local/bin/zsh"

    - name: Add desk to .bashrc
      lineinfile:
        dest: ~/.bash_profile
        line: '[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true'
        create: yes
      when: ansible_env.SHELL == "/bin/bash"

    - name: Ensure ~/.irb_history exists
      copy:
        content: ''
        dest: ~/.irb_history
        force: no
